const products = [
  {
    _id: "65757d294788fdbceef34a24",
    title: "Mens Casual Premium Slim Fit T-Shirts ",
    price: "22.3",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
    category: "Men's clothing",
    brand: "Bold Man",
    images: [
      "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a25",
    title: "Mens Cotton Jacket",
    price: "55.99",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
    category: "Men's clothing",
    brand: "Bold Man",
    images: ["https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a26",
    title: "Mens Casual Slim Fit",
    price: "15.99",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
    category: "Men's clothing",
    brand: "Bold Man",
    images: ["https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a27",
    title:
      "John Hardy WoMen's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    price: "695",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
    category: "Jewelery",
    brand: "Lock and Love",
    images: [
      "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a23",
    title: "BoMan - Foldsack No. 1 Backpack, Fits 15 Electronics",
    price: "109.95",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
    category: "Men's clothing",
    brand: "Bold Man",
    images: ["https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a29",
    title: "White Gold Plated Princess",
    price: "9.99",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
    category: "Jewelery",
    brand: "Lock and Love",
    images: [
      "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a2a",
    title: "Pierced Owl Rose Gold Plated Stainless Steel Double",
    price: "10.99",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
    category: "Jewelery",
    brand: "Lock and Love",
    images: [
      "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a2b",
    title: "Acer 2TB Elements Portable External Hard Drive - USB 3.0 ",
    price: "64",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
    category: "Electronics",
    brand: "Acer",
    images: ["https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a2c",
    title: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
    price: "109",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
    category: "Electronics",
    brand: "SanDisk",
    images: ["https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a2d",
    title:
      "HP Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
    price: "109",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
    category: "Electronics",
    brand: "HP",
    images: ["https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a2e",
    title:
      "Acer 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
    price: "114",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
    category: "Electronics",
    brand: "Acer",
    images: ["https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a2f",
    title: "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
    price: "599",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
    category: "Electronics",
    brand: "Acer",
    images: ["https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a30",
    title:
      "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ",
    price: "999.99",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
    category: "Electronics",
    brand: "Samsung",
    images: ["https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a31",
    title: "Lock and Love Women's 3-in-1 Snowboard Jacket Winter Coats",
    price: "56.99",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates",
    category: "Women's clothing",
    brand: "Lock and Love",
    images: ["https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a28",
    title: "Solid Gold Petite Micropave ",
    price: "168",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
    category: "Jewelery",
    brand: "Lock and Love",
    images: [
      "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a34",
    title: "MBJ Women's Solid Short Sleeve Boat Neck V ",
    price: "9.85",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem",
    category: "Women's clothing",
    brand: "MBJ",
    images: ["https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a33",
    title: "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
    price: "39.99",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
    category: "Women's clothing",
    brand: "MBJ",
    images: ["https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a35",
    title: "Opna Women's Short Sleeve Moisture",
    price: "7.95",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
    category: "Women's clothing",
    brand: "Opna",
    images: ["https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a36",
    title: "Opna Womens T Shirt Casual Cotton Short",
    price: "12.99",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.",
    category: "Women's clothing",
    brand: "Opna",
    images: ["https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a37",
    title: "iPhone 9",
    price: "549",
    stock: 94,
    seller: "ShopAseZ Pvt. Ltd.",
    description: "An apple mobile which is nothing like apple",
    category: "Electronics",
    brand: "Apple",
    images: [
      "https://i.dummyjson.com/data/products/1/1.jpg",
      "https://i.dummyjson.com/data/products/1/2.jpg",
      "https://i.dummyjson.com/data/products/1/3.jpg",
      "https://i.dummyjson.com/data/products/1/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a38",
    title: "iPhone X",
    price: "899",
    stock: 34,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    category: "Electronics",
    brand: "Apple",
    images: [
      "https://i.dummyjson.com/data/products/2/1.jpg",
      "https://i.dummyjson.com/data/products/2/2.jpg",
      "https://i.dummyjson.com/data/products/2/3.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a3a",
    title: "OPPOF19",
    price: "280",
    stock: 123,
    seller: "ShopAseZ Pvt. Ltd.",
    description: "OPPO F19 is officially announced on April 2021.",
    category: "Electronics",
    brand: "OPPO",
    images: [
      "https://i.dummyjson.com/data/products/4/1.jpg",
      "https://i.dummyjson.com/data/products/4/2.jpg",
      "https://i.dummyjson.com/data/products/4/3.jpg",
      "https://i.dummyjson.com/data/products/4/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a39",
    title: "Samsung Universe 9",
    price: "1249",
    stock: 36,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    category: "Electronics",
    brand: "Samsung",
    images: ["https://i.dummyjson.com/data/products/3/1.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a3b",
    title: "Huawei P30",
    price: "499",
    stock: 32,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    category: "Electronics",
    brand: "Huawei",
    images: [
      "https://i.dummyjson.com/data/products/5/1.jpg",
      "https://i.dummyjson.com/data/products/5/2.jpg",
      "https://i.dummyjson.com/data/products/5/3.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a3d",
    title: "Samsung Galaxy Book",
    price: "1499",
    stock: 50,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    category: "Electronics",
    brand: "Samsung",
    images: [
      "https://i.dummyjson.com/data/products/7/1.jpg",
      "https://i.dummyjson.com/data/products/7/2.jpg",
      "https://i.dummyjson.com/data/products/7/3.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a3c",
    title: "MacBook Pro",
    price: "1749",
    stock: 83,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "MacBook Pro 2021 with mini-LED display may launch between September, November",
    category: "Electronics",
    brand: "Apple",
    images: [
      "https://i.dummyjson.com/data/products/6/1.png",
      "https://i.dummyjson.com/data/products/6/2.jpg",
      "https://i.dummyjson.com/data/products/6/3.png",
      "https://i.dummyjson.com/data/products/6/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a3e",
    title: "HP Laptop 4",
    price: "1499",
    stock: 68,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    category: "Electronics",
    brand: "HP",
    images: [
      "https://i.dummyjson.com/data/products/8/1.jpg",
      "https://i.dummyjson.com/data/products/8/2.jpg",
      "https://i.dummyjson.com/data/products/8/3.jpg",
      "https://i.dummyjson.com/data/products/8/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a3f",
    title: "Infinix INBOOK",
    price: "1099",
    stock: 96,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
    category: "Electronics",
    brand: "Infinix",
    images: [
      "https://i.dummyjson.com/data/products/9/1.jpg",
      "https://i.dummyjson.com/data/products/9/2.png",
      "https://i.dummyjson.com/data/products/9/3.png",
      "https://i.dummyjson.com/data/products/9/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a40",
    title: "HP Pavilion 15-DK1056WM",
    price: "1099",
    stock: 89,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
    category: "Electronics",
    brand: "HP",
    images: [
      "https://i.dummyjson.com/data/products/10/1.jpg",
      "https://i.dummyjson.com/data/products/10/2.jpg",
      "https://i.dummyjson.com/data/products/10/3.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a41",
    title: "perfume Oil",
    price: "13",
    stock: 65,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
    category: "Fragrances",
    brand: "Smegr8",
    images: [
      "https://i.dummyjson.com/data/products/11/1.jpg",
      "https://i.dummyjson.com/data/products/11/2.jpg",
      "https://i.dummyjson.com/data/products/11/3.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a43",
    title: "Fog Scent Xpressio Perfume",
    price: "13",
    stock: 61,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
    category: "Fragrances",
    brand: "Xpressio",
    images: [
      "https://i.dummyjson.com/data/products/13/1.jpg",
      "https://i.dummyjson.com/data/products/13/2.png",
      "https://i.dummyjson.com/data/products/13/3.jpg",
      "https://i.dummyjson.com/data/products/13/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a42",
    title: "Brown Perfume",
    price: "40",
    stock: 52,
    seller: "ShopAseZ Pvt. Ltd.",
    description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    category: "fragrances",
    brand: "Royal_Mirage",
    images: [
      "https://i.dummyjson.com/data/products/12/1.jpg",
      "https://i.dummyjson.com/data/products/12/2.jpg",
      "https://i.dummyjson.com/data/products/12/3.png",
      "https://i.dummyjson.com/data/products/12/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a44",
    title: "Non-Alcoholic Concentrated Perfume Oil",
    price: "120",
    stock: 114,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
    category: "Fragrances",
    brand: "Smegr8",
    images: [
      "https://i.dummyjson.com/data/products/14/1.jpg",
      "https://i.dummyjson.com/data/products/14/2.jpg",
      "https://i.dummyjson.com/data/products/14/3.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a32",
    title:
      "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
    price: "29.95",
    stock: 12,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
    category: "Women's clothing",
    brand: "Lock and Love",
    images: ["https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg"],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a47",
    title: "Tree Oil 30ml",
    price: "12",
    stock: 78,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
    category: "Skincare",
    brand: "Fair & Clear",
    images: [
      "https://i.dummyjson.com/data/products/17/1.jpg",
      "https://i.dummyjson.com/data/products/17/2.jpg",
      "https://i.dummyjson.com/data/products/17/3.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a46",
    title: "Hyaluronic Acid Serum",
    price: "19",
    stock: 110,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
    category: "Skincare",
    brand: "L'Oreal Paris",
    images: [
      "https://i.dummyjson.com/data/products/16/1.png",
      "https://i.dummyjson.com/data/products/16/2.webp",
      "https://i.dummyjson.com/data/products/16/3.jpg",
      "https://i.dummyjson.com/data/products/16/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a49",
    title: "Skin Beauty Serum.",
    price: "46",
    stock: 54,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
    category: "Skincare",
    brand: "Dermive",
    images: [
      "https://i.dummyjson.com/data/products/19/1.jpg",
      "https://i.dummyjson.com/data/products/19/2.jpg",
      "https://i.dummyjson.com/data/products/19/3.png",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a48",
    title: "Oil Free Moisturizer 100ml",
    price: "40",
    stock: 88,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    category: "Skincare",
    brand: "Dermive",
    images: [
      "https://i.dummyjson.com/data/products/18/1.jpg",
      "https://i.dummyjson.com/data/products/18/2.jpg",
      "https://i.dummyjson.com/data/products/18/3.jpg",
      "https://i.dummyjson.com/data/products/18/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a4a",
    title: "Freckle Treatment Cream- 15gm",
    price: "70",
    stock: 140,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
    category: "Skincare",
    brand: "Fair & Clear",
    images: [
      "https://i.dummyjson.com/data/products/20/1.jpg",
      "https://i.dummyjson.com/data/products/20/2.jpg",
      "https://i.dummyjson.com/data/products/20/3.jpg",
      "https://i.dummyjson.com/data/products/20/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a4b",
    title: "- Daal Masoor 500 grams",
    price: "20",
    stock: 133,
    seller: "ShopAseZ Pvt. Ltd.",
    description: "Fine quality Branded Product Keep in a cool and dry place",
    category: "Groceries",
    brand: "Saaf & Khaas",
    images: [
      "https://i.dummyjson.com/data/products/21/1.png",
      "https://i.dummyjson.com/data/products/21/2.jpg",
      "https://i.dummyjson.com/data/products/21/3.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a4d",
    title: "Orange Essence Food Flavou",
    price: "14",
    stock: 26,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
    category: "Groceries",
    brand: "Dry Rose",
    images: [
      "https://i.dummyjson.com/data/products/23/1.jpg",
      "https://i.dummyjson.com/data/products/23/2.jpg",
      "https://i.dummyjson.com/data/products/23/3.jpg",
      "https://i.dummyjson.com/data/products/23/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a4e",
    title: "cereals muesli fruit nuts",
    price: "46",
    stock: 113,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
    category: "Groceries",
    brand: "Dry Rose",
    images: [
      "https://i.dummyjson.com/data/products/24/1.jpg",
      "https://i.dummyjson.com/data/products/24/2.jpg",
      "https://i.dummyjson.com/data/products/24/3.jpg",
      "https://i.dummyjson.com/data/products/24/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a4c",
    title: "Elbow Macaroni - 400 gm",
    price: "14",
    stock: 146,
    seller: "ShopAseZ Pvt. Ltd.",
    description: "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
    category: "Groceries",
    brand: "Saaf & Khaas",
    images: [
      "https://i.dummyjson.com/data/products/22/1.jpg",
      "https://i.dummyjson.com/data/products/22/2.jpg",
      "https://i.dummyjson.com/data/products/22/3.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a4f",
    title: "Gulab Powder 50 Gram",
    price: "70",
    stock: 47,
    seller: "ShopAseZ Pvt. Ltd.",
    description: "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
    category: "Groceries",
    brand: "Dry Rose",
    images: [
      "https://i.dummyjson.com/data/products/25/1.png",
      "https://i.dummyjson.com/data/products/25/2.jpg",
      "https://i.dummyjson.com/data/products/25/3.png",
      "https://i.dummyjson.com/data/products/25/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a50",
    title: "Plant Hanger For Home",
    price: "41",
    stock: 131,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
    category: "Home-decoration",
    brand: "Flying Wooden",
    images: [
      "https://i.dummyjson.com/data/products/26/1.jpg",
      "https://i.dummyjson.com/data/products/26/2.jpg",
      "https://i.dummyjson.com/data/products/26/3.jpg",
      "https://i.dummyjson.com/data/products/26/4.jpg",
      "https://i.dummyjson.com/data/products/26/5.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a51",
    title: "Flying Wooden Bird",
    price: "51",
    stock: 17,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
    category: "Home-decoration",
    brand: "Flying Wooden",
    images: [
      "https://i.dummyjson.com/data/products/27/1.jpg",
      "https://i.dummyjson.com/data/products/27/2.jpg",
      "https://i.dummyjson.com/data/products/27/3.jpg",
      "https://i.dummyjson.com/data/products/27/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a52",
    title: "3D Embellishment Art Lamp",
    price: "20",
    stock: 54,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
    category: "Home-decoration",
    brand: "Golden",
    images: [
      "https://i.dummyjson.com/data/products/28/1.jpg",
      "https://i.dummyjson.com/data/products/28/2.jpg",
      "https://i.dummyjson.com/data/products/28/3.png",
      "https://i.dummyjson.com/data/products/28/4.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a53",
    title: "Handcraft Chinese style",
    price: "60",
    stock: 7,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
    category: "Home-decoration",
    brand: "Golden",
    images: [
      "https://i.dummyjson.com/data/products/29/1.jpg",
      "https://i.dummyjson.com/data/products/29/2.jpg",
      "https://i.dummyjson.com/data/products/29/3.webp",
      "https://i.dummyjson.com/data/products/29/4.webp",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a54",
    title: "Key Holder",
    price: "30",
    stock: 54,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Attractive Design Metallic material Four key hooksReliable & DurablePremium Quality",
    category: "Home-decoration",
    brand: "Golden",
    images: [
      "https://i.dummyjson.com/data/products/30/1.jpg",
      "https://i.dummyjson.com/data/products/30/2.jpg",
      "https://i.dummyjson.com/data/products/30/3.jpg",
    ],
    __v: 0,
  },
  {
    _id: "65757d294788fdbceef34a45",
    title: "Eau De Perfume Spray",
    price: "30",
    stock: 105,
    seller: "ShopAseZ Pvt. Ltd.",
    description:
      "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
    category: "Fragrances",
    brand: "Smegr8",
    images: [
      "https://i.dummyjson.com/data/products/15/1.jpg",
      "https://i.dummyjson.com/data/products/15/2.jpg",
      "https://i.dummyjson.com/data/products/15/3.jpg",
      "https://i.dummyjson.com/data/products/15/4.jpg",
    ],
    __v: 0,
  },
];

const categories = [
  {
    _id: "65757a59555b7f970ed229f6",
    categoryName: "Electronics",
    brands: [
      "Apple",
      "Samsung",
      "HP",
      "Infinix",
      "Huawei",
      "OPPO",
      "Acer",
      "SanDisk",
    ],
    __v: 0,
    imageUrl: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
  },
  {
    _id: "65757a59555b7f970ed229f7",
    categoryName: "Jewelery",
    brands: ["Lock and Love"],
    __v: 0,
    imageUrl:
      "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
  },
  {
    _id: "65757a59555b7f970ed229f8",
    categoryName: "Men's clothing",
    brands: ["BoMan"],
    __v: 0,
    imageUrl: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
  },
  {
    _id: "65757a59555b7f970ed229f9",
    categoryName: "Women's clothing",
    brands: ["Lock and Love", "MBJ", "Opna"],
    __v: 0,
    imageUrl: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
  },
  {
    _id: "65757a59555b7f970ed229fa",
    categoryName: "Home-decoration",
    brands: ["Flying Wooden, Golden"],
    __v: 0,
    imageUrl: "https://i.dummyjson.com/data/products/26/1.jpg",
  },
  {
    _id: "65757a59555b7f970ed229fb",
    categoryName: "Skincare",
    brands: ["L'Oreal Paris", "Fair & Clear", "Dermive"],
    __v: 0,
    imageUrl: "https://i.dummyjson.com/data/products/17/1.jpg",
  },
  {
    _id: "65757a59555b7f970ed229fc",
    categoryName: "Groceries",
    brands: ["Saaf & Khaas", "Dry Rose"],
    __v: 0,
    imageUrl: "https://i.dummyjson.com/data/products/21/1.png",
  },
  {
    _id: "65757a59555b7f970ed229fd",
    categoryName: "Fragrances",
    brands: ["Smegr8", "Royal_Mirage", "Xpressio"],
    __v: 0,
    imageUrl: "https://i.dummyjson.com/data/products/11/1.jpg",
  },
];

module.exports = { products, categories };
